### ISSUE TITLE
Runtime environment

### ISSUE THREAD

**Issue by NucciTheBoss** [NucciTheBoss/intro_to_hpc_hackpsu#1]
### Description

Create environment for attendees to use as an experimental Linux cluster. Here is what should be installed:

- `Python >= 3.5`
- `Dask`
- `Numba`
- `OpenMPI >= 3`
- `mpi4py`
- `Lmod`

Going to use Docker as the backend for running the container. Base image will be `Ubuntu 20.04.04`.

### Tasks

- [x] Build Docker image
- [x] Publish to Docker Hub
- [x] Write specification for container (i.e. what software is installed inside).
- [x] Write instructions in the README for installing Docker locally

**Comment by NucciTheBoss** [comment]
Think about having folks install LXD instead of directly installing Docker on their computer. Might be much easier for WIndows users.

**Comment by NucciTheBoss** [comment]
Have finished this. Now onto the examples
