### ISSUE TITLE
Python Examples

### ISSUE THREAD

**Issue by NucciTheBoss** [NucciTheBoss/intro_to_hpc_hackpsu#2]
### Description

Write brief examples for each of the three frameworks I am going to highlight. Here is what I am trying to highlight:

- `mpi4py`
- `Numba`
- `Dask`

Each of these technologies are important to HPC as they help take Python to the next level. Order of preference for presenting: `mpi4py` -> `Numba` -> `Dask`. 

### Tasks

- [ ] Find easy examples that demonstrate performance improvement
- [ ] Grab a dataset that can be analyzed by all three technologies
- [ ] Write completed solutions for all three
- [ ] Strip out certain parts of the solutions to create digestible examples
- [ ] Test individually
- [ ] Have a friend test to make sure it is digestible
