### ISSUE TITLE
Slide Deck

### ISSUE THREAD

**Issue by NucciTheBoss** [NucciTheBoss/intro_to_hpc_hackpsu#3]
### Description

Slide deck that I will work off of during the workshop. Hoping to have the following flow:

1. Brief Introduction
2. Install Docker while I talk
3. Discuss the foundations of HPC (why do we need it, common tech stack, who uses it, companies involved, etc.)
4. Exploring the Docker container
5. Exploring mpi4py
6. Exploring Numba
7. Exploring Dask
8. Where to go from here

I need to make sure that I absolutely time myself while for each of the slides since I have a limited amount of time.

### Tasks

- [x] Choose theming for slide deck
- [x] Create slide deck
- [x] General edits and revisions
- [x] Go through it with someone from ICDS
- [x] Go through it with one of my friends (does it make sense?)

**Comment by NucciTheBoss** [comment]
Presentation done. Julie liked it.
